"""change tag column to accept null

Revision ID: 06d2b4552e4a
Revises: 378eb9fe7a07
Create Date: 2026-02-24 15:52:13.767322

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d2b4552e4a'
down_revision: Union[str, Sequence[str], None] = '378eb9fe7a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'instruction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'instruction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
