"""add tables and changes to delivery_partner table

Revision ID: 24f241dce1ec
Revises: ec19e037ed5b
Create Date: 2026-02-17 12:52:03.523942

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f241dce1ec'
down_revision: Union[str, Sequence[str], None] = 'ec19e037ed5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('servicable_location',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.zip_code'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['delivery_partner.id'], ),
    sa.PrimaryKeyConstraint('partner_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicable_location')
    op.drop_table('location')
    # ### end Alembic commands ###
