"""add new tables

Revision ID: 378eb9fe7a07
Revises: 24f241dce1ec
Create Date: 2026-02-19 14:29:53.182507

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378eb9fe7a07'
down_revision: Union[str, Sequence[str], None] = '24f241dce1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('FRAGILE', 'PERISHABLE', 'EXPRESS', 'SIGNATURE_REQUIRED', 'PARCEL', 'ELECTRONICS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'shipment_id')
    )
    op.add_column('orders', sa.Column('estimated_delivery', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_delivery')
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
